extends:
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
env:
  node: true
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 7
plugins:
  - prettier
rules:
  prettier/prettier:
    - "error"
  import/no-extraneous-dependencies:
    - "error"
    - devDependencies: true
  import/prefer-default-export: 0
